"""
services/meeting_service.py
────────────────────────────
In-memory meeting store. No database needed yet — everything lives in a
Python dict. When Riddhima's team sets up Supabase/PostgreSQL we just
swap this module's implementation without touching the routes.

Each meeting entry:
{
    "id":           str,
    "status":       "active" | "ended",
    "started_at":   ISO-8601 string,
    "ended_at":     ISO-8601 string | None,
    "transcript":   [ { start, end, text, speaker, language, language_probability } ],
    "summary":      str | None,
    "decisions":    [ str ],
    "action_items": [ { task, owner, deadline } ]
}
"""

import uuid
from datetime import datetime
import json
import os
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "meetings_db.json"

def _load_db() -> dict:
    if DB_PATH.exists():
        try:
            with open(DB_PATH, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

def _save_db(meetings: dict):
    with open(DB_PATH, "w", encoding="utf-8") as f:
        json.dump(meetings, f, indent=2)

# ─────────────────────────────────────────────────────────────────────────────
# CRUD
# ─────────────────────────────────────────────────────────────────────────────

def create_meeting() -> dict:
    _meetings = _load_db()
    meeting_id = str(uuid.uuid4())
    _meetings[meeting_id] = {
        "id":           meeting_id,
        "status":       "active",
        "started_at":   datetime.now().isoformat(),
        "ended_at":     None,
        "transcript":   [],
        "summary":      None,
        "decisions":    [],
        "action_items": []
    }
    _save_db(_meetings)
    print(f"[MeetingService] Created meeting: {meeting_id}")
    return _meetings[meeting_id]


def create_meeting_with_id(meeting_id: str, tab_url: str = "") -> dict:
    """Used by the WebSocket to create a meeting with an ID generated by the extension."""
    _meetings = _load_db()
    _meetings[meeting_id] = {
        "id":           meeting_id,
        "status":       "active",
        "started_at":   datetime.now().isoformat(),
        "ended_at":     None,
        "tab_url":      tab_url,
        "transcript":   [],
        "summary":      None,
        "decisions":    [],
        "action_items": []
    }
    _save_db(_meetings)
    print(f"[MeetingService] Created meeting from extension: {meeting_id}")
    return _meetings[meeting_id]


def get_meeting(meeting_id: str) -> dict | None:
    _meetings = _load_db()
    return _meetings.get(meeting_id)


def end_meeting(meeting_id: str) -> dict | None:
    _meetings = _load_db()
    meeting = _meetings.get(meeting_id)
    if not meeting:
        return None
    meeting["status"]   = "ended"
    meeting["ended_at"] = datetime.now().isoformat()
    _save_db(_meetings)
    print(f"[MeetingService] Ended meeting: {meeting_id}")
    return meeting


def list_meetings() -> list:
    """Return all meetings (summary view — no full transcript)."""
    _meetings = _load_db()
    return [
        {
            "id":             m["id"],
            "status":         m["status"],
            "started_at":     m["started_at"],
            "ended_at":       m["ended_at"],
            "has_transcript": len(m.get("transcript", [])) > 0,
            "has_summary":    bool(m.get("summary") and m["summary"] != "Analysis failed — see server logs."),
        }
        for m in _meetings.values()
    ]


# ─────────────────────────────────────────────────────────────────────────────
# Transcript
# ─────────────────────────────────────────────────────────────────────────────

def add_transcript(meeting_id: str, transcript_result: dict, speaker: str = "unknown") -> bool:
    """
    Store transcription output from TranscriptionService.transcribe().
    Merges each segment with meeting_id and speaker info.
    """
    _meetings = _load_db()
    meeting = _meetings.get(meeting_id)
    if not meeting:
        return False

    for seg in transcript_result.get("segments", []):
        meeting["transcript"].append({
            "meeting_id":           meeting_id,
            "speaker":              speaker,
            "start":                seg["start"],
            "end":                  seg["end"],
            "text":                 seg["text"],
            "language":             seg.get("language",             transcript_result.get("language")),
            "language_probability": seg.get("language_probability", transcript_result.get("language_probability"))
        })

    _save_db(_meetings)
    print(f"[MeetingService] Added {len(transcript_result.get('segments', []))} segments to {meeting_id}")
    return True


def get_transcript(meeting_id: str) -> list | None:
    _meetings = _load_db()
    meeting = _meetings.get(meeting_id)
    if not meeting:
        return None
    return meeting["transcript"]


# ─────────────────────────────────────────────────────────────────────────────
# AI Results
# ─────────────────────────────────────────────────────────────────────────────

def save_ai_results(meeting_id: str, summary: str, decisions: list, action_items: list, sentiment_score: int = 50) -> bool:
    _meetings = _load_db()
    meeting = _meetings.get(meeting_id)
    if not meeting:
        return False
    meeting["summary"]         = summary
    meeting["decisions"]       = decisions
    meeting["action_items"]    = action_items
    meeting["sentiment_score"] = sentiment_score
    _save_db(_meetings)
    return True